#+OPTIONS: H:2 ':t *:t
#+OPTIONS: org-confirm-babel-evaluate:nil
#+TITLE: Transforming 2010 Nebraska General Election Results
#+AUTHOR: Steven R. Dunbar
#+EMAIL: sdunbarne@gmail.edu

* Meta-Data
** State Overview
- Name State: Nebraska
- Metadata Status:  up-to-date as of April 23, 2018
- Overview Field: state data gathering process was easy, 2010 data
  provided by Jacob Fricke, Elections Specialist I, in the Nebraska
  Secretary of State's Office in an email to Steve Dunbar on 
  The data was in the form of a CSV file, "2010 General Election by Precinct.csv"
** Data Source
- Organization: 2010 data in 1 single CSV file, statewide with per-line
  information by precinct,
  provided by Jacob Fricke, Elections Specialist I, in the Nebraska
  Secretary of State's Office in an email to Steve Dunbar on April 17, 2018.
- Portal Link: http://www.sos.ne.gov/dyindex.html#boxingName
- Direct Link:  But also see
  http://www.sos.ne.gov/elec/pdf/2010%20Gen%20Canvass%20Book%2011-30-Final.pdf
- Results Type: Certified results by county at 
  http://www.sos.ne.gov/elec/pdf/2010%20Gen%20Canvass%20Book%2011-30-Final.pdf
- Formats:  2010 data in statewide format with precinct level
  information in CSV format
  provided by Jacob Fricke, Elections Specialist I, in the Nebraska
  Secretary of State's Office in an email to Steve Dunbar on April 17, 2018.
** Election Metadata
- Start and end date: Start: November 2, 2010, End: November 2, 2010 
- Race type: General
- Special:   No
- Primary Type: Not Applicable
- Primary Note: Not Applicable
- Absentee and Provisional:  Result files include vote counts for these types: Yes!
** Offices Covered
- President:  No
- US Senate: No
- US House: Yes
- Governor: Yes
- State Officers: Yes
- State Legislators: Unicameral State Senators.  Note that the
  Legislature is composed of 49 members, chosen by a single-member
  district or constituency. Senators are chosen for four-year terms,
  with one-half of the seats up for election every second year.
** Results Breakdown
- Race-wide:  No top-level tabulation, use statistical or spreadsheet
  software for totaling, sub-totaling, etc.
- County:  Yes, results are tabulated by county.
- Precinct:  Yes,  results are tabulated by precinct.
- Congressional District: Yes, presidential or statewide offices are
  tabulated by Congressional district
  For details on the 2010 Congressional Districts, see:
https://ballotpedia.org/Redistricting_in_Nebraska_after_the_2010_census
- State legislative: Presidential and statewide offices are NOT
  tabulated by state legislative district
- Note:  Not applicable, no notes.
** Notes
*** DONE Congressional Districts in Cedar County
    CLOSED: [2018-05-20 Sun 14:49]
In 2010, Cedar County was split over Congressional District 1 and
Congressional District 3.  Precincts 0005, 0010, 0014, 0015, 0016,
0017 are in Congressional District 1.   The remaining precincts 
0011, 0012, 0013, 0006, 0007, 0008, 0009, 0001, 0002, 0003,
0004 are in Congressional District 3.

Note that Precinct 0017 is the "Provisional/Absentee" precinct and in
the mapping of Congressional Districts to precincts this precinct gets
assigned to both Districts twice and the second overwrites the
first. This requires a special correction which accounts for the
special case attended to in the cleaning of the original CSV file to
the file form for Openelections.
*** DONE Congressional Districts in Sarpy County
    CLOSED: [2018-05-20 Sun 14:49]
In 2010, Sarpy County was split over Congressional District 1 and
Congressional District 2.  Precincts 0035, 0036, 0037, 0040, 0080, 0052, 0051, 0079, 0068, 0069
0070, 0071, 0084, 0085, 0086, 0072
are in Congressional District 1.   

The remaining precincts 
0025, 0026, 0027, 0028, 0029, 0030, 0031, 0001, 0002, 0003
0004, 0005, 0006, 0007, 0008, 0009, 0010, 0011, 0012, 0013
0014, 0034, 0015, 0016, 0017, 0018, 0019, 0020, 0021, 0022
0023, 0024, 0032, 0033, 0038, 0039, 0041, 0042, 0043, 0044
0045, 0046, 0047, 0048, 0049, 0050, 0081, 0082, 0083, 0053
0054, 0055, 0077, 0078, 0056, 0057, 0058, 0059, 0060, 0061
0062, 0063, 0064, 0065, 0066, 0067, 0087, 0073, 0074, 0075
and, 0076  are in Congressional, District, 2.

*** DONE Maps for Nebraska Legislative Districts
    CLOSED: [2018-05-20 Sun 12:01]
A comprehensive map of Nebraska Legislative Districts in 2010, relative to
Nebraska counties, is at
http://nebraskaccess.ne.gov/LegPastPresent/2002-2003.pdf
Scroll down the page for the finer details about the Omaha, Lincoln
and Grand Island district outlines.   
*** DONE Sarpy County Precincts Split over Congressional Districts
    CLOSED: [2018-06-08 Fri 16:16]
    In the 2010 election, there are no Sarpy County precincts which are
    split over two Congressional Districts.  This is in contrast to
    elections after 2010 in which   
    Precincts 19 and 21 in Sarpy County are split over Congressional
    District 1 and Congressional District 2.  

Here's the code that establishes the fact, starting from the original
CSV file
#+BEGIN_SRC R
  gen2010 <- read_csv("2010 General Election by Precinct.csv")
  sarpy <- filter(gen2010, County=="Sarpy")
  sarpyCong <- filter(sarpy, grepl("FED", X9))
  sarpyCongRep <-  filter(sarpyCong, Party=="REP1")
  fort <-  select(filter(sarpyCongRep, CandidateLast=="Fortenberry"), PrecinctID)
  terry <- select(filter(sarpyCongRep, CandidateLast=="Terry"), PrecinctID)
  intersect(fort, terry)
#+END_SRC
*** DONE Counties with no races for Legislature 
    CLOSED: [2018-06-08 Fri 16:17]
    Note that the Legislature is composed of 49 members, chosen by a
    single-member district or constituency. Senators are chosen for
    four-year terms, with one-half of the seats up for election every
    second year.  In fact, in 2010 it is 24 even numbered legislative
    districts which have races.  Many counties, particularly in the
    rural and western parts of Nebraska are completely subsumed in one
    legislative district.  As a consequence of these two facts, some
    counties have no races for Legislature.
*** DONE Counties with Multiple Legislative Districts
    CLOSED: [2018-06-08 Fri 16:26]

    Some populous counties have multiple Legislative Districts
    contained within them, for example, Douglas, Sarpy and Lancaster.
    Because Senators are chosen for four-year terms, with one-half of
    the seats up for election every second year, these counties with
    multiple Legislative Districts will have some precincts reporting
    a positive number of votes, usually in the tens or hundreds of
    votes for a real race.  Some precincts in a county with multiple
    legislative districts will not report any Legislative race results,
    because the legislative district is not up for election.

*** DONE Special Note about Vote Totals including Furnas County
    CLOSED: [2018-06-08 Fri 17:35]

In doing the checking of vote totals from this transformed cvs data, I
noticed that some vote totals differed from the official Secretary of
State Canvass Book.  The differences were about 9, 10, or 11 votes for
Republicans and about 1 or 2 votes for Democrats.  Upon further
checking, the races for there were differences of the totals for the
data from the Canvass Report always involved Furnas County, typically
in a statewide race such as for Governor.  Further, noted in the
official Canvas Report on page 2 under Reported Problems is the
statement:

#+BEGIN_QUOTE
Furnas County: The County Clerk misread or misinterpreted the Lower
Republican NRD certification and provided all voters in Furnas County
both Lower Republican NRD Subdistrict 1 and Subdistrict 2 ballots.
The error was discovered after the original certification to the
Secretary of State.  The County Clerk submitted a supplemental
certification removing the improper votes from each race total.  The
Subdistrict 2 race was uncontested (only 1 candidate) so the error did
not impact the outcome of the race.  Although the Subdistrict 1 race
was contested, the error did not change the outcome.
#+END_QUOTE

It is likely that that the CSV data does not contain about 12 of the
ballots from Furnas County due to this County Clerk error.  I see no
satisfactory way to resolve the error, so I let it stand.

*** DONE Special Note about Cedar County
    CLOSED: [2018-06-08 Fri 17:35]

 In 2010, precincts 1,2,3,4,6,7,8,9,11,12,13 in Cedar County (a rural
 county in the extreme northeast corner of the state)  were in
 Congressional District 3.  The remaining precincts 5, 10, 14, 15, 16
 were in Congressional District 1.  Precinct 17 is the Early/Absentee
 precinct, and ballots cast Early/Absentee could be from either Congressional
 District.  The original algorithmic extraction of the Congressional District
 (described below) did not respect this fine point, and testing and
 error checking discovered counting some votes for the three Congressional
 District 3 candidates reported in Congressional District 1.  The fix
 for this error is to reach into these three candidate lines and explicitly correct
 the Precinct 17 Cedar County lines for them to be in Congressional
 District 3.  This accounts for the special case attention paid to
 Cedar County Precinct 17 in the data transformation.

* Target Format
** Common Fields in Results files
From http://docs.openelections.net/common-fields/: Each election year
represents a directory containing data files covering elections
occurring in that year. Each election held during that year contains
one record for each candidate listed in the results. The resulting
CSV-file records consist of these fields: county, precinct, office,
district, party, candidate, votes.  The OpenElections CSV layout
approach is to mirror the results file as much as possible, with one
exception: we try to have a single result on each line, rather than
multiple candidates or precincts.
** Comment about tidy data
General comment:  The format specified in the section "Common Fields
in Results Files" seems to conform to the tidyverse
conventions as I understand them.
* Data Transformation Strategy
1.  Load the R tidyverse library.
2.  Read in the offices tracked in this transformation.
3.  Read in original csv data with tidyverse function read_csv.
    This results in a tibble: 87,281 x 16, parsed with column specification:
cols(
  X1 = col_integer(),
  CountyID = col_integer(),
  County = col_character(),
  PrecinctID = col_character(),
  PrecinctName = col_character(),
  X6 = col_integer(),
  RaceName = col_character(),
  X8 = col_character(),
  X9 = col_character(),
  X10 = col_character(),
  X11 = col_integer(),
  X12 = col_integer(),
  CandidateFirst = col_character(),
  CandidateLast = col_character(),
  Party = col_character(),
  Votes = col_integer()
)

4.  Map each precinct (row) to its associated Congressional District in the 
following way: 
a.  Find those precincts (rows) which were a FEDeral
election for a Congressional Representative having a REP1 candidate.
b.  Make a smaller tibble containing only the needed columns.
c.  Create a new column CtyPrec by concatenating the County name with the
Precinct ID.  This becomes a unique identifier for each precinct.
d.  Change X9 by picking off the last character in column X9, which is
the Congressional District.  
e.  Make an associative list of CtyPrec
with the Congressional District.  
f.  Fill a new column CongDistrict
in gen2010 using the Congressional District associated with CtyPrec.
5.  Reduce the number of columns considered with
%>% select(County, PrecinctID, RaceName, X9, X10, Party, CandidateFirst, CandidateLast, Votes)
6. Reduce the number of rows considered to only the offices I am
   following with
%>% filter(grepl(offices, RaceName))
After this filter, the tibble is reduced to 20,668 x 9
7. Paste the Candidate Names together to get one column with
%>% mutate(Candidate = paste(CandidateFirst, CandidateLast))

8.  Clean up the Party column, because the Party is read in as a 4-character
   string ending with a spurious 1.  Clean this column with
%>% mutate(Party = substr(Party,1,3))

9. Clean up the RaceName column, because RaceName has a superfluous
   4-character string "For " at the beginning of each entry.
   Therefore, keep only from position 5 to the end of the string.
%>% mutate(Office = substr(RaceName, 5, length(RaceName)))
The RaceName will still be longer than the office column used
previously for 2014, 2012 data, but that will be transformed later.


10. The precincts are reported by a 4-digit precinct ID and by precinct name, if
   the precinct has a name, but note that not all precincts have a
   name.  However, when the original source CSV file was created,
   these two
   fields were split incorrectly and the last character of the
   reported PrecinctID is the first character of the PrecinctName, if
   present.  This means many, but not all PrecinctID's are longer than
   4 characters.  If so, transfrom the Precinct with
%>% mutate(Precinct = ifelse(nchar(PrecinctID) > 4, substr(PrecinctID,1,4), PrecinctID))

11. In the original source CSV file the field which gets read in as
    X10 is actually the last character (if present) of what should
    have been field X9.  If not present, it gets read in as "NA".  In
    any case, paste the two fields back together and take care of
    "NA" later.
mutate(X9 = paste0(X9, X10)) %>%

12.  Extract out the Legislative District information.  For Statewide
    races, the field X9 starts with "SW".  For Congressional races in
    2010, the field X9 starts out with "FED".  For Legislative races,
    which start with "LEG: 
    the Legislative District is the last element of field X9.  So
    extract each as appropriate:
mutate(legdist=ifelse(grepl("LEG", X9), 
       substr(X9,nchar(X9)-2, nchar(X9)), substr(X9, 1,3))) %>%

13.  Finally, select only the columns required for the final tibble
    and rename according to OpenElections standards.
select(county = County, precinct = Precinct, office = Office, 
       district = District, party = Party, candidate = Candidate, votes = Votes, legdist)

14.  Final clean-up;
a.  Clean up the Legislative Districts by omitting white space and
spurious NA.
b.  Reduce the Governors Race title to just Governor for consistency
with 2012 and 2014 openelections data for Nebraska.
c.  Likewise reduce Representative,
d.  Likewise reduce Auditor
e.  Likewise reduce Legislature.

15.  Apply explicit fix to Congressional Disctrict 3 races in
     Cedar County Precinct 0017 (Early/Absentee) to
     correctly reassign those districts to Congressional District 3.
16.  Write the openelections format CSV file.

* R Script to Read, Transform, and Write 2010 Results
#+BEGIN_SRC R :tangle t
  library(tidyverse)
  offices <- "Representative|Governor|Secretary of State|State Treasurer|Attorney General|Auditor|Legislature"


  gen2010 <- read_csv("2010 General Election by Precinct.csv")

  distmap <- gen2010 %>% filter(grepl("FED", X9) & Party=="REP1") %>%
      select(County, PrecinctID, X9) %>%
      mutate(CtyPrec = paste0(County, PrecinctID)) %>%
      mutate(X9 = substr(X9, nchar(X9), nchar(X9))) 
  distList <- setNames(distmap$X9, distmap$CtyPrec)

  gen2010 <- mutate(gen2010, CtyPrec = paste0(County, PrecinctID))
  gen2010 <- mutate(gen2010, CongDist = distList[CtyPrec])

  ne2010  <-gen2010 %>% 
              select(County, PrecinctID, RaceName, X9, X10, CongDist, Party, CandidateFirst, CandidateLast, Votes) %>%
              filter(grepl(offices, RaceName)) %>%
              mutate(Candidate = paste(CandidateFirst, CandidateLast)) %>%
              mutate(Party = substr(Party,1,3)) %>% 
              mutate(Office = substr(RaceName, 5, length(RaceName))) %>% 
              mutate(Precinct = ifelse(nchar(PrecinctID) > 4, substr(PrecinctID,1,4), PrecinctID)) %>%
              mutate(X9 = paste0(X9, X10)) %>%
              mutate(legdist=ifelse(grepl("LEG", X9), 
                              substr(X9,nchar(X9)-2, nchar(X9)), substr(X9, 1,3))) %>%
              select(county = County, precinct = Precinct, office = Office, 
                     district = CongDist, party = Party, candidate = Candidate, votes = Votes, legdist)

    ne2010 <- ne2010 %>%
              mutate(legdist = sub(" ", "", legdist)) %>%
              mutate(legdist = sub("NA", "", legdist)) %>%
              mutate(office = ifelse(grepl("Governor", office),       substr(office,1, 8),  office)) %>%
              mutate(office = ifelse(grepl("Representative", office), substr(office,1, 14), office)) %>%
              mutate(office = ifelse(grepl("Auditor", office),        substr(office,1, 7),  office)) %>%
              mutate(office = ifelse(grepl("Legislature", office),    substr(office,15,25), office))

   ne2010 <- ne2010 %>%
             mutate(district =
               ifelse(county=="Cedar" & precinct=="0017" 
                      & grepl("Smith|Davis|Hill", candidate), 
               3, district))
   write_csv(ne2010, "20101102_ne_general_statewide_precinct.csv", delim=",")
#+END_SRC
** Quality Assurance

*** District One Representative

**** Burt County
| County | Fortenberry | Harper |
|--------+-------------+--------|
|        | REP         | DEM    |
| Burt   | 1854        | 679    |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Burt" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Ivy Harper       |  679 |
| Jeff Fortenberry | 1854 |

**** Totals
| Totals | Fortenberry | Harper |
|--------+-------------+--------|
|        | REP         | DEM    |
|        | 116,871     | 47106  |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, district=="1" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Ivy Harper       |  47106 |
| Jeff Fortenberry | 116871 |

*** District Two Representative

**** Sarpy County
| County | Terry | White |
|--------+-------+-------|
|        | REP   | DEM   |
| Sarpy  | 20456 | 9354  |

Total  93840   60486
#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Sarpy" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Ivy Harper       |  1697 |
| Jeff Fortenberry |  6776 |
| Lee Terry        | 20456 |
| Tom White        |  9354 |

**** Totals

| Totals | Terry | White |
|--------+-------+-------|
|        | REP   | DEM   |
|        | 93840 | 68486 |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, district=="2" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Lee Terry | 93840 |
| Tom White | 60486 |

*** District Three Representative
**** York County
| County | Smith | Davis | Hill     |
|--------+-------+-------+----------|
|        | REP   | DEM   | Petition |
| York   | 3217  | 538   | 277      |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="York" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Adrian Smith  | 3217 |
| Dan Hill      |  277 |
| Rebekah Davis |  538 |

**** Furnas County
| County | Smith | Davis | Hill     |
|--------+-------+-------+----------|
|        | REP   | DEM   | Petition |
| Furnas | 1439  | 263   | 138      |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="Representative"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Adrian Smith  | 1428 |
| Dan Hill      |  138 |
| Rebekah Davis |  262 |

**** Totals

| Totals | Terry  | White | Hill     |
|--------+--------+-------+----------|
|        | REP    | DEM   | Petition |
|        | 117275 | 29932 | 20036    |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, district=="3" & office=="Representative"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Adrian Smith  | 117264 |
| Dan Hill      |  20036 |
| Rebekah Davis |  29931 |

*** Governor
**** Furnas County
| County | Heineman | Meister |
|--------+----------+---------|
|        | REP      | DEM     |
| Furnas | 1546     | 300     |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="Governor"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Dave Heineman, Governor | 1535 |
| Mike Meister, Governor  |  299 |


**** Totals

| County | Heineman | Meister |
|--------+----------+---------|
|        | REP      | DEM     |
| Totals | 360,645  | 127343  |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, office=="Governor"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Dave Heineman, Governor | 360634 |
| Mike Meister, Governor  | 127342 |

*** Secretary of State
**** Furnas County
| County | Heineman | Meister |
|--------+----------+---------|
|        | REP      | DEM     |
| Furnas | 1482     | 285     |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="Secretary of State"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Janet Stewart |  284 |
| John A. Gale  | 1472 |

**** Totals

| County | Gale   | Stewart |
|--------+--------+---------|
|        | REP    | DEM     |
| Totals | 326431 | 141564  |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, office=="Secretary of State"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Janet Stewart | 141563 |
| John A. Gale  | 326421 |

*** Attorney General
**** Furnas County
| County | Bruning |
|--------+---------|
|        | REP     |
| Furnas | 1664    |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="Attorney General"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Jon Bruning | 1652 |

**** Totals

| County | Bruning |
|--------+---------|
|        | REP     |
| Totals | 393124  |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, office=="Attorney General"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Jon Bruning | 393115 |

***  State Treasurer
**** Furnas County
| County | Stenberg | Stoj |
|--------+----------+------|
|        | REP      | DEM  |
| Furnas | 1529     | 266  |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="State Treasurer"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Don Stenberg | 1518 |
| Mark Stoj    |  265 |

**** Totals

| County | Stenberg | Stoj   |
|--------+----------+--------|
|        | REP      | DEM    |
| Totals | 345661   | 128231 |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, office=="State Treasurer"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Don Stenberg | 345650 |
| Mark Stoj    | 128230 |

***  Auditor
**** Furnas County
| County | Foley | Sallach-Grace |
|--------+-------+---------------|
|        | REP   | DEM           |
| Furnas | 1461  | 205           |

#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, county=="Furnas" & office=="Auditor"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Michele Sallach-Grace |  205 |
| Mike Foley            | 1449 |

**** Totals

| County | Foley  | Sallach-Grace |
|--------+--------+---------------|
|        | REP    | DEM           |
| Totals | 345436 | 88433         |


#+BEGIN_SRC R :session *R*
summarize( group_by( filter(ne2010, office=="Auditor"), candidate), totals = sum(votes, na.rm=TRUE))
#+END_SRC

#+RESULTS:
| Michele Sallach-Grace |  88433 |
| Mike Foley            | 345424 |

*** Legislature District 14

**** Sarpy County

| County | Smith | Whitehead |
|--------+-------+-----------|
|        | REP   | DEM       |
| Totals | 6203  | 4995      |

#+BEGIN_SRC R :session *R*
 summarize( group_by( filter(ne2010, county=="Sarpy", legdist=="14"), candidate), totals = sum(votes))
#+END_SRC

#+RESULTS:
| Jim Smith        | 6203 |
| Teresa Whitehead | 4995 |

*** All Legislative Races
#+BEGIN_SRC R
test <- filter(ne2010, office=="Legislature")
summarize( group_by(test, legdist, candidate), totals = sum(votes))
#+END_SRC
